# Generated by Django 4.1.7 on 2023-05-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayAndWin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lottodrop',
        ),
    ]
