# Generated by Django 4.1.7 on 2023-04-05 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('invited_by_id', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('invited_user', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('wallet', models.IntegerField(default=0)),
                ('total_earnings', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('date_time_of_joining', models.DateTimeField(auto_now_add=True)),
                ('level_1_count', models.IntegerField(default=0)),
                ('level_2_count', models.IntegerField(default=0)),
                ('level_3_count', models.IntegerField(default=0)),
                ('level_4_count', models.IntegerField(default=0)),
                ('level_5_count', models.IntegerField(default=0)),
                ('level_6_count', models.IntegerField(default=0)),
                ('level_7_count', models.IntegerField(default=0)),
                ('level_1_earnings', models.IntegerField(default=0)),
                ('level_2_earnings', models.IntegerField(default=0)),
                ('level_3_earnings', models.IntegerField(default=0)),
                ('level_4_earnings', models.IntegerField(default=0)),
                ('level_5_earnings', models.IntegerField(default=0)),
                ('level_6_earnings', models.IntegerField(default=0)),
                ('level_7_earnings', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
