# Generated by Django 4.1.7 on 2023-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='invited_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
