# Generated by Django 4.1.7 on 2023-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_invited_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='refunded_amount',
            field=models.IntegerField(blank=0, default=0, null=0),
        ),
    ]
