# Generated by Django 4.1.7 on 2023-04-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='dep',
        ),
        migrations.DeleteModel(
            name='Dep',
        ),
        migrations.DeleteModel(
            name='pro',
        ),
    ]
