# Generated by Django 4.1.7 on 2023-04-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0004_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
