# Generated by Django 4.1.7 on 2023-04-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
