# Generated by Django 4.1.7 on 2023-04-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0010_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
