# Generated by Django 4.1.7 on 2023-04-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0013_remove_orderitem_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
