# Generated by Django 4.1.7 on 2023-04-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0015_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
