# Generated by Django 4.1.7 on 2023-04-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0017_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
