# Generated by Django 4.1.7 on 2023-04-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0019_carouselimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImages',
        ),
    ]
