# Generated by Django 4.1.7 on 2023-04-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0022_rename_image_1_carouselimages_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImages',
        ),
    ]
