# Generated by Django 4.1.7 on 2023-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0023_delete_carouselimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='carousel')),
                ('image_2', models.ImageField(upload_to='carousel')),
                ('image_3', models.ImageField(upload_to='carousel')),
            ],
        ),
    ]
