# Generated by Django 4.1.7 on 2023-04-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0027_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time_of_Payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
