# Generated by Django 4.1.7 on 2023-04-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0029_alter_order_coin_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
