# Generated by Django 4.1.7 on 2023-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0031_order_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
