# Generated by Django 4.1.7 on 2023-04-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0033_bankaccountdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdetails',
            name='withdraw_requested',
            field=models.BooleanField(default=False),
        ),
    ]
