# Generated by Django 4.1.7 on 2023-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0034_bankaccountdetails_withdraw_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cancelled_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
