# Generated by Django 4.1.7 on 2023-05-22 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userHomePage', '0035_order_order_cancelled_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReturnOrdersRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_Date', models.DateTimeField(blank=True, null=True)),
                ('return_Amount', models.CharField(blank=True, max_length=255, null=True)),
                ('return_requested', models.BooleanField(default=False)),
                ('return_success', models.BooleanField(default=False)),
                ('returned_Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userHomePage.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
