# Generated by Django 4.1.7 on 2023-05-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0040_order_order_return_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returned_order_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
