# Generated by Django 4.1.7 on 2023-05-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0041_order_returned_order_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnordersbankdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='returnordersbankdetails',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userHomePage.returnordersrefund'),
        ),
    ]
