# Generated by Django 4.1.7 on 2023-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0042_remove_returnordersbankdetails_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returned_order_refunde_requested',
            field=models.BooleanField(default=False),
        ),
    ]
