# Generated by Django 4.1.7 on 2023-05-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0043_order_returned_order_refunde_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='returned_order_refunde_requested',
            new_name='returned_order_refund_requested',
        ),
    ]
