# Generated by Django 4.1.7 on 2023-05-25 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userHomePage', '0045_alter_order_order_expected_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnordersbankdetails',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userHomePage.order'),
        ),
    ]
