# Generated by Django 4.1.7 on 2023-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfilePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraws',
            name='withdraw_status',
            field=models.BooleanField(default=False),
        ),
    ]
