# Generated by Django 4.1.7 on 2023-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfilePage', '0003_withdraws_withdrawed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraws',
            name='date_time_of_withdraw_requested',
            field=models.DateTimeField(),
        ),
    ]
