# Generated by Django 4.1.7 on 2023-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfilePage', '0005_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
