# Generated by Django 4.1.7 on 2023-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfilePage', '0006_contactus_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
