# Generated by Django 4.1.7 on 2023-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='cart_value',
            field=models.IntegerField(default=0),
        ),
    ]
