# Generated by Django 4.1.7 on 2023-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_affiliatecommission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecommission',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
