# Generated by Django 4.1.7 on 2023-04-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_affiliatecommission_failed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffiliateCommission',
        ),
    ]
