# Generated by Django 4.1.7 on 2023-04-19 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userHomePage', '0032_order_tracking_id_title'),
        ('products', '0006_delete_affiliatecommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_title', models.CharField(blank=True, max_length=255, null=True)),
                ('commission', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userHomePage.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
